title: Conconi Family BioDevice Foundry
description: Shared research facility at UBC for biomedical device fabrication, prototyping, biofunctionalization, and characterization.
url: "https://bobperryRPL.github.io"
baseurl: "/BiodeviceSite"

markdown: kramdown
permalink: pretty

collections:
  capabilities:
    output: true
    permalink: /capabilities/:name/
  staff:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: capabilities
    values:
      layout: capability

include:
  - _redirects
  - _headers

exclude:
  - admin
  - CLF Template
  - new site template
  - ubc_signature_design_package
